"""Added about_me to User model

Revision ID: 2afcd8a938bf
Revises: 2741a3f06722
Create Date: 2024-07-17 13:00:06.092739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afcd8a938bf'
down_revision = '569e8b9e1117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['surname'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('about_me')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
