"""Added oauth column to user model

Revision ID: 569e8b9e1117
Revises: 751d8ccaf1ae
Create Date: 2024-07-17 10:33:55.928460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569e8b9e1117'
down_revision = '751d8ccaf1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_provider_user_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('oauth_provider_user_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
