"""Initial migration

Revision ID: 6c46eb3a0b63
Revises: 06d816b3331c
Create Date: 2024-09-05 16:53:42.463324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c46eb3a0b63'
down_revision = '06d816b3331c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_amenity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_amenity', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
