"""Added about_me to User model

Revision ID: 7263a46a2ff7
Revises: 72484a209721
Create Date: 2024-07-17 13:54:11.227105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7263a46a2ff7'
down_revision = '72484a209721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', mysql.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
