"""Added image column

Revision ID: 751d8ccaf1ae
Revises: 23029481c99b
Create Date: 2024-07-15 17:28:07.770237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751d8ccaf1ae'
down_revision = '23029481c99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
