"""add username to listing model

Revision ID: 8055f2887917
Revises: 9790cec59339
Create Date: 2024-09-21 14:14:50.824105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8055f2887917'
down_revision = '9790cec59339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('uname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uname', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
