"""Add city to listings

Revision ID: 848efec3fbce
Revises: a4adf1e4fc6d
Create Date: 2024-07-31 15:50:15.519948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848efec3fbce'
down_revision = 'a4adf1e4fc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
