"""added price to list column

Revision ID: 9334fc4dd364
Revises: c69a02365eb5
Create Date: 2024-07-20 14:55:32.865021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9334fc4dd364'
down_revision = 'c69a02365eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_currency')

    # ### end Alembic commands ###
