"""Add state to listings

Revision ID: a4adf1e4fc6d
Revises: 9cf8de484038
Create Date: 2024-07-31 14:21:14.774981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4adf1e4fc6d'
down_revision = '9cf8de484038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
