"""Add member_since to User model

Revision ID: c3b96f456e78
Revises: d6b3461c67d9
Create Date: 2024-07-17 14:56:01.035945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3b96f456e78'
down_revision = 'd6b3461c67d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_since', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('image_file',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=225),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=225),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_suspended')
        batch_op.drop_column('is_banned')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_message_read_time')
        batch_op.drop_column('member_since')

    # ### end Alembic commands ###
